build:
  nodes:
    analysis:
      project_setup:
        override: true
      tests:
        override: [py-scrutinizer-run]
    coverage:
      tests:
        before:
          - pip install coverage
        override:
          - command: "coverage run -m unittest discover -s tests"
            coverage:
              file: ".coverage"

  environment:
    python:
      version: "3.6.13"

filter:
  paths:
    - "sqlalchemy_mutable/*"